config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'welcome/index'
  root 'welcome#index'
  get '/contests/:id', to: 'contest#show', as: 'contest'
  post 'contests/:contest_id/strategies', to: 'strategy#create', as: :create_strategy
  post 'contests/:contest_id/game_sessions', to: 'game_session#create', as: :create_game_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contest.rb
class Contest < ApplicationRecord
  belongs_to :game_mechanic
  has_many :strategies
end

app/models/game_mechanic.rb
class GameMechanic < ApplicationRecord
  has_many :contests
end

app/models/strategy.rb
class Strategy < ApplicationRecord
  belongs_to :contest
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :strategies, inverse_of: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contest_controller.rb
class ContestController < ApplicationController
  def show
    @contest = Contest.joins(:game_mechanic).includes(:game_mechanic).find(params[:id])
  end
end

app/controllers/game_session_controller.rb
class GameSessionController < ApplicationController
  def create
    CustomGameSessionWorker.perform_async(current_user.id)
  end
end

app/controllers/strategy_controller.rb
class StrategyController < ApplicationController
  def create
    @source_text = !params[:text].blank? ? params[:text] : params[:file].read
    @strategy = Strategy.new(
      source: @source_text,
      user: current_user,
      version: 0, # TODO: increment version
      contest_id: params[:contest_id]
    )
    @strategy.save
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @contests = Contest.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contest_helper.rb
module ContestHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contest/show.html.erb
<% content_for :breadcrumb do %>
  <li>
    <%= link_to 'ai-contester', :root %>
  </li>
  <li class="active">
    <%= @contest.name %>
  </li>
<% end %>

<%= simple_format(@contest.description).html_safe %>

<a target="_blank" href="<%= @contest.game_mechanic.url %>">
  <%= @contest.game_mechanic.url %>
</a>
<% if user_signed_in? %>
  <%= form_tag(create_strategy_path(contest_id: @contest.id), method: "post", multipart: true) do %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <div class="h2">
      Отправить стратегию
    </div>
    <div class="form-group">
      <label>
        Текстом
      </label>
      <textarea class="form-control" name="text"></textarea>
    </div>
    <div class="form-group">
      <label>
        Файлом
        <input class="form-control-file" type="file" name="file" />
      </label>
    </div>
    <button type="submit" class="btn btn-primary">Отправить</button>
  <% end %>

  <%= form_tag(create_game_session_path(contest_id: @contest.id), method: "post", multipart: true) do %>
    <button type="submit" class="btn btn-primary">Создать игровую сессию</button>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContesterSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="page-header row">
        <div class="col-md-9">
          <h1>
            AI-Contester
            <br/>
            <small>Соревнования для программистов в игровом формате</small>
          </h1>
        </div>
        <div class="col-md-3">
          <% if user_signed_in? %>
            <div class="panel panel-info user_signed_in_panel">
              <div class="panel-heading">
                <%= current_user.email %>
              </div>
              <div class="list-group">
                <div class="list-group-item text-right">
                  <%= link_to 'Выйти', destroy_user_session_path, :method => :delete, :class => 'btn btn-default' %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>

        <% if !user_signed_in? %>
          <div class="panel panel-warning row">
            <div class="panel-heading">
              Вы не вошли в систему.
              Войдите или зарегистрируйтесь, чтобы участвовать в соревнованиях.
            </div>
            <div class="panel-body">
              <%= link_to 'Вход', new_user_session_path %>
              /
              <%= link_to 'Регистрация', new_user_registration_path %>
            </div>
          </div>
        <% end %>
      <ol class="breadcrumb row">
        <%= yield :breadcrumb %>
      </ol>
      <div class=row>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<% content_for :breadcrumb do %>
  <li class="active">
    ai-contester
  </li>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    Активные соревнования
  </div>
  <div class="list-group">
    <% @contests.each do |contest| %>
      <div class="list-group-item">
        <h3>
          <%= contest.name %>
          <br/>
          <small><%= simple_format(contest.description).html_safe %></small>
        </h3>
        <div class='text-right'>
          <%= link_to 'Присоединиться', contest, :class => 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>